HeronEngine.exe tests\factorial.heron
HeronEngine.exe tests\fib.heron
HeronEngine.exe tests\sieve.heron
HeronEngine.exe tests\squares.heron
HeronEngine.exe tests\test-closures.heron
HeronEngine.exe tests\test-constructor.heron
HeronEngine.exe tests\test-duck-typing.heron
HeronEngine.exe tests\test-if.heron
HeronEngine.exe tests\test-field.heron
HeronEngine.exe tests\test-for-loop.heron
HeronEngine.exe tests\test-function-call.heron
HeronEngine.exe tests\test-inheritance.heron
HeronEngine.exe tests\test-inherited-constructor.heron
HeronEngine.exe tests\test-interfaces.heron
HeronEngine.exe tests\test-output.heron
HeronEngine.exe tests\test-random.heron
HeronEngine.exe tests\test-return.heron
HeronEngine.exe tests\test-viewport.heron
HeronEngine.exe tests\test-while.heron
HeronEngine.exe tests\hello-world.heron
HeronEngine.exe tests\factorial.heron